2022-12-15 14:34:05.953 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-15 14:34:14.299 | ERROR    | services.explorer.explorer:get_order_history:142 - Failed to get order history, cookie may have expired
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 301, in run
    promotions = self.preload()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 269, in preload
    self.ph.get_oder_history(ctx_cookies=self._ctx_cookies)
  File "/home/runner/work/freegame/freegame/epic/src/services/explorer/explorer.py", line 219, in get_oder_history
    if resp := explorer.get_order_history(ctx_cookies):
> File "/home/runner/work/freegame/freegame/epic/src/services/explorer/explorer.py", line 140, in get_order_history
    raise RequestException("Failed to get order history, cookie may have expired")
requests.exceptions.RequestException: Failed to get order history, cookie may have expired
2022-12-15 14:34:57.360 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1865), thread 'MainThread' (139769896840064):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 557, in cart_handle_payment
    if self._click_order_button(page):  # cart_handle_payment
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 456, in _click_order_button
    payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//div[@id='webPurchaseContainer']//iframe"
============================================================
2022-12-15 14:45:59.827 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-15 14:46:06.716 | ERROR    | services.explorer.explorer:get_order_history:142 - Failed to get order history, cookie may have expired
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 301, in run
    promotions = self.preload()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 269, in preload
    self.ph.get_oder_history(ctx_cookies=self._ctx_cookies)
  File "/home/runner/work/freegame/freegame/epic/src/services/explorer/explorer.py", line 219, in get_oder_history
    if resp := explorer.get_order_history(ctx_cookies):
> File "/home/runner/work/freegame/freegame/epic/src/services/explorer/explorer.py", line 140, in get_order_history
    raise RequestException("Failed to get order history, cookie may have expired")
requests.exceptions.RequestException: Failed to get order history, cookie may have expired
2022-12-15 14:46:49.703 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1882), thread 'MainThread' (140311148948544):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 557, in cart_handle_payment
    if self._click_order_button(page):  # cart_handle_payment
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 456, in _click_order_button
    payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//div[@id='webPurchaseContainer']//iframe"
============================================================
2022-12-15 15:55:59.946 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-15 15:56:35.728 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1775), thread 'MainThread' (140098254695296):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2022-12-17 06:27:27.355 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-17 06:28:02.078 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1920), thread 'MainThread' (139793392090176):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2022-12-22 06:27:15.743 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-22 06:27:50.014 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1818), thread 'MainThread' (140246740732992):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2022-12-24 06:27:44.626 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-24 06:28:20.293 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1852), thread 'MainThread' (140510261660736):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2022-12-29 06:27:16.752 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-29 06:27:51.553 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1953), thread 'MainThread' (140471457528896):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2022-12-31 06:26:36.810 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2022-12-31 06:27:12.039 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1966), thread 'MainThread' (139936395197312):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2023-01-05 06:28:37.423 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-01-05 06:29:13.167 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1832), thread 'MainThread' (139826756086656):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2023-01-07 06:27:57.193 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-01-07 06:28:31.546 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1868), thread 'MainThread' (140476703505472):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2023-01-12 06:29:09.298 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-01-12 06:29:43.513 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1861), thread 'MainThread' (140285277232192):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2023-01-14 06:26:14.387 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1818), thread 'MainThread' (139635121433472):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 81, in get_label
    self.prompt = frame_challenge.locator("//h2[@class='prompt-text']").text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 10000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//iframe[contains(@title, 'hCaptcha挑战')]"
  selector resolved to hidden <iframe scrolling="no" frameborder="0" aria-hidden="true…></iframe>
waiting for selector "//iframe[contains(@title, 'hCaptcha挑战')] >> internal:control=enter-frame >> //h2[@class='prompt-text']"
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 108, in job_loop_claim
    with UnrealClaimerInstance(self.silence, log_ignore=log_ignore) as claimer:
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 164, in __enter__
    fire(  # token
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 708, in refresh_ctx_cookies
    resp = self.armor.anti_hcaptcha(page, window="login", recur_url=recur_url)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 251, in anti_hcaptcha
    self.get_label(frame_challenge)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 85, in get_label
    raise ChallengePassed("Man-machine challenge unexpectedly passed")
hcaptcha_challenger.exceptions.ChallengePassed: Message: Man-machine challenge unexpectedly passed

2023-01-19 06:28:28.405 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-01-19 06:29:02.734 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1789), thread 'MainThread' (139768084200512):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2023-01-21 06:26:52.116 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-01-21 06:27:26.042 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1778), thread 'MainThread' (139982062898240):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
2023-01-26 06:25:13.671 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2023-01-26 06:25:28.149 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2023-01-26 06:25:28.262 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1897), thread 'MainThread' (139833468636224):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 108, in job_loop_claim
    with UnrealClaimerInstance(self.silence, log_ignore=log_ignore) as claimer:
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 164, in __enter__
    fire(  # token
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 708, in refresh_ctx_cookies
    resp = self.armor.anti_hcaptcha(page, window="login", recur_url=recur_url)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=sunflower.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
2023-01-28 06:27:32.565 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-01-28 06:28:06.655 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1785), thread 'MainThread' (140144003984448):
Traceback (most recent call last):
  File "/home/runner/work/freegame/freegame/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/freegame/freegame/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/freegame/freegame/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/freegame/freegame/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/freegame/freegame/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/freegame/freegame/epic/src/services/bricklayer/core.py", line 571, in unreal_activate_payment
    if page.locator(".cart-amount").text_content() != "0":
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15059, in text_content
    self._sync(self._impl_obj.text_content(timeout=timeout))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 526, in text_content
    return await self._frame.text_content(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 598, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".cart-amount"
============================================================
